modLoader="javafml"
loaderVersion="[34,)"
license="All rights reserved"
issueTrackerURL="https://github.com/fallOut015/pact_magic/issues"
[[mods]]
modId="pact_magic"
version="${file.jarVersion}"
displayName="Pact Magic"
updateJSONURL="https://github.com/fallOut015/pact_magic/blob/master/src/main/resources/updateJSONURL.json"
displayURL="https://www.curseforge.com/minecraft/mc-mods/pact-magic"
logoFile="logoFile.png"
credits="Thanks to Mojang Studios, Forge, the people who's tutorials I followed, and the people who I call friends."
authors="fallOut015"
description='''
Adds new Angels and Demons to summon.
'''
[[dependencies.pact_magic]]
    modId="forge"
    mandatory=true
    versionRange="[34,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.pact_magic]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.3]"
    ordering="NONE"
    side="BOTH"
